# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

table_cpp <- function(v, sort_data = FALSE) {
    .Call('_spartaco_table_cpp', PACKAGE = 'spartaco', v, sort_data)
}

MetropolisAllocationC <- function(x, Cs, Ds, Uglob, Dglob, Dist, Mu, Tau, Xi, Alpha, Beta, Phi, maxit = 10L, min_obs = 3L, prob_choices = as.numeric( c(0.5,0.5)), print_info = 0L) {
    .Call('_spartaco_MetropolisAllocationC', PACKAGE = 'spartaco', x, Cs, Ds, Uglob, Dglob, Dist, Mu, Tau, Xi, Alpha, Beta, Phi, maxit, min_obs, prob_choices, print_info)
}

rcpparma_hello_world <- function() {
    .Call('_spartaco_rcpparma_hello_world', PACKAGE = 'spartaco')
}

rcpparma_outerproduct <- function(x) {
    .Call('_spartaco_rcpparma_outerproduct', PACKAGE = 'spartaco', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_spartaco_rcpparma_innerproduct', PACKAGE = 'spartaco', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_spartaco_rcpparma_bothproducts', PACKAGE = 'spartaco', x)
}

